/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;
import tablasDivisas.*;

/**
 *
 * @author Jesus
 */
public class DivisasView extends javax.swing.JPanel {
    
    static TablaDolar dolar;
    static TablaEuro euro;
    static TablaLibra libra;
    static TablaSol sol;
    static TablaWon won;
    static TablaYen yen;
    /**
     * Creates new form DivisasView
     */
    public DivisasView() {
        initComponents();
        InitTables();
    }
    
    public static void InitTables(){
        dolar = new TablaDolar();
        euro = new TablaEuro();
        libra = new TablaLibra();
        sol = new TablaSol();
        won = new TablaWon();
        yen = new TablaYen();
    }
    public static double getValorMoneda(TablaDivisa tabla, String moneda) {
        return tabla.GetValue(moneda);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMontoDivisa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboOrigenDivisa = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnConvertirDivisa = new javax.swing.JLabel();
        txtResultadoDivisa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboDestinoDivisa = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(35, 34, 34));
        jPanel1.setPreferredSize(new java.awt.Dimension(614, 397));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingresa el monto que quieres convertir:");

        txtMontoDivisa.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtMontoDivisa.setForeground(new java.awt.Color(153, 153, 153));
        txtMontoDivisa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMontoDivisa.setText("S/. 0.00");
        txtMontoDivisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMontoDivisaMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Divisa de destino");

        comboOrigenDivisa.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        comboOrigenDivisa.setForeground(new java.awt.Color(102, 102, 102));
        comboOrigenDivisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dolar", "Euro", "Libra Esterlina", "Yen Japones", "Won Sur-Coreano", "Sol" }));

        jPanel2.setBackground(new java.awt.Color(0, 99, 82));

        btnConvertirDivisa.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        btnConvertirDivisa.setForeground(new java.awt.Color(255, 255, 255));
        btnConvertirDivisa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnConvertirDivisa.setText("CONVERTIR");
        btnConvertirDivisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConvertirDivisaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConvertirDivisaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConvertirDivisaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnConvertirDivisa, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnConvertirDivisa, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
        );

        txtResultadoDivisa.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtResultadoDivisa.setForeground(new java.awt.Color(153, 153, 153));
        txtResultadoDivisa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtResultadoDivisa.setText("Resultado...");

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Divisa de origen");

        comboDestinoDivisa.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        comboDestinoDivisa.setForeground(new java.awt.Color(102, 102, 102));
        comboDestinoDivisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dolar", "Euro", "Libra Esterlina", "Yen Japones", "Won Sur-Coreano", "Sol" }));
        comboDestinoDivisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDestinoDivisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(txtMontoDivisa, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboOrigenDivisa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtResultadoDivisa)
                            .addComponent(comboDestinoDivisa, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtMontoDivisa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboOrigenDivisa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboDestinoDivisa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(txtResultadoDivisa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboDestinoDivisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDestinoDivisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDestinoDivisaActionPerformed

    private void btnConvertirDivisaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConvertirDivisaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConvertirDivisaMouseEntered

    private void btnConvertirDivisaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConvertirDivisaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConvertirDivisaMouseExited

    private void btnConvertirDivisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConvertirDivisaMouseClicked
        // TODO add your handling code here:
        double monto = Double.parseDouble(txtMontoDivisa.getText());
        String monedaOrigen =(String) comboOrigenDivisa.getSelectedItem() ;
        String monedaDestino = (String) comboDestinoDivisa.getSelectedItem();
        double  valorMoneda = 0.0;
        switch (monedaOrigen){
            case "Dolar":
                valorMoneda = getValorMoneda(dolar, monedaDestino);
                
                txtResultadoDivisa.setText(String.format("%.2f",(monto / valorMoneda)));
                System.out.println("La conversion de " + monto + " " + monedaOrigen + " a " + monedaDestino + " es de: " + String.format("%.2f",(monto / valorMoneda)));
                System.out.println(monto);
                System.out.println(dolar.GetValue(monedaDestino));
                
                System.out.println(sol.GetValue(monedaDestino));
                System.out.println(monedaDestino);
                break;

            case "Euro":
                valorMoneda = getValorMoneda(euro, monedaDestino);
                txtResultadoDivisa.setText(String.format("%.2f",(monto / valorMoneda)));
                System.out.println("La conversion de " + monto + " " + monedaOrigen + " a " + monedaDestino + " es de: " + String.format("%.2f",(monto / valorMoneda)));
                break;
            case "Libra Esterlina":
                valorMoneda = getValorMoneda(libra, monedaDestino);
                txtResultadoDivisa.setText(String.format("%.2f",(monto / valorMoneda)));
                System.out.println("La conversion de " + monto + " " + monedaOrigen + " a " + monedaDestino + " es de: " + String.format("%.2f",(monto / valorMoneda)));
                break;
            case "Yen Japones":
                valorMoneda = getValorMoneda(yen, monedaDestino);
                txtResultadoDivisa.setText(String.format("%.2f",(monto / valorMoneda)));
                System.out.println("La conversion de " + monto + " " + monedaOrigen + " a " + monedaDestino + " es de: " + String.format("%.2f",(monto / valorMoneda)));
                break;
            case "Sol":
                valorMoneda = getValorMoneda(sol, monedaDestino);
                txtResultadoDivisa.setText(String.format("%.2f",(monto / valorMoneda)));
                System.out.println("La conversion de " + monto + " " + monedaOrigen + " a " + monedaDestino + " es de: " + String.format("%.2f",(monto / valorMoneda)));
                
                break;
            case "Won Sur-Coreano":
                valorMoneda = getValorMoneda(won, monedaDestino);
                txtResultadoDivisa.setText(String.format("%.2f",(monto / valorMoneda)));
                System.out.println("La conversion de " + monto + " " + monedaOrigen + " a " + monedaDestino + " es de: " + String.format("%.2f",(monto / valorMoneda)));
                break;
            default:
                System.out.println("No se pudo completar");
        }
    }//GEN-LAST:event_btnConvertirDivisaMouseClicked

    private void txtMontoDivisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMontoDivisaMouseClicked
        // TODO add your handling code here:
        txtMontoDivisa.setText("");
    }//GEN-LAST:event_txtMontoDivisaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnConvertirDivisa;
    private javax.swing.JComboBox<String> comboDestinoDivisa;
    private javax.swing.JComboBox<String> comboOrigenDivisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtMontoDivisa;
    private javax.swing.JTextField txtResultadoDivisa;
    // End of variables declaration//GEN-END:variables
}
